// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCCy_bdWs2wZjDca6_7jvePzWv4KmMRg',
    appId: '1:1064722173770:web:5048b899d22b62e7a73bb3',
    messagingSenderId: '1064722173770',
    projectId: 'event-ticket-maker',
    authDomain: 'event-ticket-maker.firebaseapp.com',
    storageBucket: 'event-ticket-maker.firebasestorage.app',
    measurementId: 'G-XGGW64315R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuR8Sz9fWYzOiih1xRH2BzuDVw7OkLIcY',
    appId: '1:1064722173770:android:43b89451cbd06e1ba73bb3',
    messagingSenderId: '1064722173770',
    projectId: 'event-ticket-maker',
    storageBucket: 'event-ticket-maker.firebasestorage.app',
  );
}
